language: c

env:
  - LUA=""
  - LUA="luajit"

install:
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install luafilesystem
  - sudo luarocks install busted
  - sudo luarocks install luacov-coveralls --server=http://rocks.moonscript.org/dev

script: "busted --randomize -c --output=TAP spec"

after_success:
   - luacov-coveralls -c spec/.luacov
